// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Chirp struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Body      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type RefreshToken struct {
	Token     string
	UserID    uuid.UUID
	ExpiresAt time.Time
	RevokedAt sql.NullTime
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type User struct {
	ID        uuid.UUID
	Email     string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	Password  string
}
